<?php 

$productos = array(
  1 => array(
    "id" => 1,
    "id_marca" => 1,
    "id_categoria" => 1,
    "precio" => 2300,
    "nombre" => "Remera nike",
    "talles" => array("S - M"),
    "descripcion" => "Remera negra nike de algodón",
    "imagen" => "../img/nike_negra.jpg",
    "destacado" => true,
  ),
  2 => array(
    "id" => 2,
    "id_marca" => 3,
    "id_categoria" => 2,
    "precio" => 2500,
    "nombre" => "Pantalón puma",
    "talles" => array("S - M - L - XXL"),
    "descripcion" => "Pantalón puma relajado",
    "imagen" => "../img/pantalon_puma1.jpg",
    "destacado" => false,
  ),
  3 => array(
    "id" => 3,
    "id_marca" => 1,
    "id_categoria" => 2,
    "precio" => 3000,
    "nombre" => "Pantalón nike",
    "talles" => array("M - L"),
    "descripcion" => "Pantalón nike cómodo",
    "imagen" => "../img/pantalon_nike1.jpg",
    "destacado" => true,
  ),
  4 => array(
    "id" => 4,
    "id_marca" => 1,
    "id_categoria" => 3,
    "precio" => 8000,
    "nombre" => "Zapatilla nike",
    "talles" => array("10 - 9.5 - 9"),
    "descripcion" => "Zapatilla takawishi pirusa",
    "imagen" => "../img/zapatilla_nike1.jpg",
    "destacado" => false,
  ),
  5 => array(
    "id" => 5,
    "id_marca" => 3,
    "id_categoria" => 1,
    "precio" => 2200,
    "nombre" => "Remera puma",
    "talles" => array("S - M"),
    "descripcion" => "Remera puma tira blanca",
    "imagen" => "../img/remera_puma1.jpg",
    "destacado" => true,
  ),
  6 => array(
    "id" => 6,
    "id_marca" => 3,
    "id_categoria" => 3,
    "precio" => 7200,
    "nombre" => "Zapatilla puma",
    "talles" => array("10 - 9 - 8.5"),
    "descripcion" => "Zapatilla rsx-221 anase",
    "imagen" => "../img/zapatilla_puma1.jpg",
    "destacado" => false,
  ),
  7 => array(
    "id" => 7,
    "id_marca" => 2,
    "id_categoria" => 1,
    "precio" => 2000,
    "nombre" => "Remera adidas",
    "talles" => array("S - M - L - XL - XXL"),
    "descripcion" => "Remera adidas x Pharrell Williams",
    "imagen" => "../img/remera_adidas1.jpg",
    "destacado" => true,
  ),
  8 => array(
    "id" => 8,
    "id_marca" => 2,
    "id_categoria" => 2,
    "precio" => 3000,
    "nombre" => "Pantalón adidas",
    "talles" => array("S - XL - XXL"),
    "descripcion" => "Pantalón adidas de entrenamiento",
    "imagen" => "../img/pantalon_adidas1.jpg",
    "destacado" => false,
  ),
  9 => array(
    "id" => 9,
    "id_marca" => 2,
    "id_categoria" => 3,
    "precio" => 7400,
    "nombre" => "Zapatilla adidas",
    "talles" => array("10.5 - 9"),
    "descripcion" => "Zapatila adidas boost Yeezy 700 OG",
    "imagen" => "../img/zapatilla_adidas1.jpg",
    "destacado" => false,
  ),
  10 => array(
    "id" => 10,
    "id_marca" => 4,
    "id_categoria" => 1,
    "precio" => 1800,
    "nombre" => "Remera reebok",
    "talles" => array("M - L"),
    "descripcion" => "Remera crossfit reebok",
    "imagen" => "../img/remera_reebok1.jpg",
    "destacado" => true,
  ),
  11 => array(
    "id" => 11,
    "id_marca" => 4,
    "id_categoria" => 2,
    "precio" => 2500,
    "nombre" => "Pantalón reebok",
    "talles" => array("S - M - L"),
    "descripcion" => "Pantalón casual reebok",
    "imagen" => "../img/pantalon_reebok1.jpg",
    "destacado" => false,
  ),
  12 => array(
    "id" => 12,
    "id_marca" => 4,
    "id_categoria" => 3,
    "precio" => 5600,
    "nombre" => "Zapatilla reebok",
    "talles" => array("10 - 10.5 - 9.5"),
    "descripcion" => "Zapatilla reebok Allen Iverson 2003",
    "imagen" => "../img/zapatilla_reebok1.jpg",
    "destacado" => false,
  ),
  13 => array(
    "id" => 13,
    "id_marca" => 5,
    "id_categoria" => 1,
    "precio" => 2200,
    "nombre" => "Remera asics",
    "talles" => array("XS - S - M"),
    "descripcion" => "Remera asics de entrenamiento prolongado",
    "imagen" => "../img/remera_asics1.jpg",
    "destacado" => true,
  ),
  14 => array(
    "id" => 14,
    "id_marca" => 5,
    "id_categoria" => 2,
    "precio" => 3300,
    "nombre" => "Pantalón casual asics",
    "talles" => array("S - L - XL"),
    "descripcion" => "Pantalón Asics",
    "imagen" => "../img/pantalon_asics1.jpg",
    "destacado" => false,
  ),
  15 => array(
    "id" => 15,
    "id_marca" => 5,
    "id_categoria" => 3,
    "precio" => 7500,
    "nombre" => "Zapatilla Asics GEL LYTE ",
    "talles" => array("11 - 10 - 9.5 - 9"),
    "descripcion" => "Zapatilla asics",
    "imagen" => "../img/zapatilla_asics1.jpg",
    "destacado" => false,
  ),  
);

$puntero = fopen("../../data/productos.json", "w");

$productosJSON = json_encode($productos);

fwrite($puntero,$productosJSON,strlen($productosJSON));

fclose($puntero);


?>
