<?php 

$productos = array(
  1 => array(
    "id" => 1,
    "id_marca" => 1,
    "id_categoria" => 1,
    "precio" => 2300,
    "nombre" => "Remera nike",
    "talles" => array(""),
    "descripcion" => "Remera negra nike de algodón",
    "imagen" => "../img/nike_negra.jpg",
    "destacado" => true,
  ),
  2 => array(
    "id" => 2,
    "id_marca" => 3,
    "id_categoria" => 2,
    "precio" => 2500,
    "nombre" => "Pantalón puma",
    "talles" => array(""),
    "descripcion" => "Pantalón puma",
    "imagen" => "../img/pantalon_puma1.jpg",
    "destacado" => false,
  ),
  3 => array(
    "id" => 3,
    "id_marca" => 1,
    "id_categoria" => 2,
    "precio" => 3000,
    "nombre" => "Pantalón nike",
    "talles" => array(""),
    "descripcion" => "Pantalón nike",
    "imagen" => "../img/pantalon_nike1.jpg",
    "destacado" => true,
  ),
  4 => array(
    "id" => 4,
    "id_marca" => 1,
    "id_categoria" => 3,
    "precio" => 8000,
    "nombre" => "Zapatilla nike",
    "talles" => array(""),
    "descripcion" => "Pantalón nike",
    "imagen" => "../img/zapatilla_nike1.jpg",
    "destacado" => false,
  ),
  5 => array(
    "id" => 5,
    "id_marca" => 3,
    "id_categoria" => 1,
    "precio" => 2200,
    "nombre" => "Remera puma",
    "talles" => array(""),
    "descripcion" => "Remera puma",
    "imagen" => "../img/remera_puma1.jpg",
    "destacado" => true,
  ),
  6 => array(
    "id" => 6,
    "id_marca" => 3,
    "id_categoria" => 3,
    "precio" => 7200,
    "nombre" => "Zapatilla puma",
    "talles" => array(""),
    "descripcion" => "Zapatilla puma",
    "imagen" => "../img/zapatilla_puma1.jpg",
    "destacado" => false,
  ),
  7 => array(
    "id" => 7,
    "id_marca" => 2,
    "id_categoria" => 1,
    "precio" => 2000,
    "nombre" => "Remera adidas",
    "talles" => array(""),
    "descripcion" => "Remera adidas",
    "imagen" => "../img/remera_adidas1.jpg",
    "destacado" => true,
  ),
  8 => array(
    "id" => 8,
    "id_marca" => 2,
    "id_categoria" => 2,
    "precio" => 3000,
    "nombre" => "Pantalón adidas",
    "talles" => array(""),
    "descripcion" => "Pantalón adidas",
    "imagen" => "../img/pantalon_adidas1.jpg",
    "destacado" => false,
  ),
  9 => array(
    "id" => 9,
    "id_marca" => 2,
    "id_categoria" => 3,
    "precio" => 7400,
    "nombre" => "Zapatilla adidas",
    "talles" => array(""),
    "descripcion" => "Zapatila adidas",
    "imagen" => "../img/zapatilla_adidas1.jpg",
    "destacado" => false,
  ),
  10 => array(
    "id" => 10,
    "id_marca" => 4,
    "id_categoria" => 1,
    "precio" => 1800,
    "nombre" => "Remera reebok",
    "talles" => array(""),
    "descripcion" => "Remera reebok",
    "imagen" => "../img/remera_reebok1.jpg",
    "destacado" => true,
  ),
  11 => array(
    "id" => 11,
    "id_marca" => 4,
    "id_categoria" => 2,
    "precio" => 2500,
    "nombre" => "Pantalón reebok",
    "talles" => array(""),
    "descripcion" => "Pantalón reebok",
    "imagen" => "../img/pantalon_reebok1.jpg",
    "destacado" => false,
  ),
  12 => array(
    "id" => 12,
    "id_marca" => 4,
    "id_categoria" => 3,
    "precio" => 5600,
    "nombre" => "Zapatilla reebok",
    "talles" => array(""),
    "descripcion" => "Zapatilla reebok",
    "imagen" => "../img/zapatilla_reebok1.jpg",
    "destacado" => false,
  ),
  13 => array(
    "id" => 13,
    "id_marca" => 5,
    "id_categoria" => 1,
    "precio" => 2200,
    "nombre" => "Remera asics",
    "talles" => array(""),
    "descripcion" => "Remera asics",
    "imagen" => "../img/remera_asics1.jpg",
    "destacado" => true,
  ),
  14 => array(
    "id" => 14,
    "id_marca" => 5,
    "id_categoria" => 2,
    "precio" => 3300,
    "nombre" => "Pantalón asics",
    "talles" => array(""),
    "descripcion" => "Pantalón asics",
    "imagen" => "../img/pantalon_asics1.jpg",
    "destacado" => false,
  ),
  15 => array(
    "id" => 15,
    "id_marca" => 5,
    "id_categoria" => 3,
    "precio" => 7500,
    "nombre" => "Zapatilla asics",
    "talles" => array(""),
    "descripcion" => "Zapatilla asics",
    "imagen" => "../img/zapatilla_asics1.jpg",
    "destacado" => false,
  ),  
);

$puntero = fopen("../../data/productos.json", "w");

$productosJSON = json_encode($productos);

fwrite($puntero,$productosJSON,strlen($productosJSON));

fclose($puntero);


?>
